import { Product, Category, Collection } from "./types";

export const categories: Category[] = [
  {
    id: "men",
    name: "Men",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBErcqmTbzx8latwT4vwwQvQ8RrDPUnUlJ8BYLQPCVe7K7q00YR8MjUpsvfD0N6XWI8TtHdxbwL-oebmstj0_Y2tzpmTVcY1diBaIsTYCyZ1N3LntHoZfW43mhj1PVCtIca1ReF4nL8V9Ato_GDYfeo0rfrBzgKah9GzZXanK-uWyShtjPAuddRE_2LYzfovmfZJLooH_FumXNPXxc2DmrLgHc9cq0JwqZwbPnlRdn7yiKEKdYOjtHUag",
    count: 24,
  },
  {
    id: "women",
    name: "Women",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB9rSJ6NWXqJeOuddQm-MrTHumMcv2BWgzra678XBd5CX4Jn_bE2SahdRbySv8kUTWLfIj3--w1G-Go5clF0yiDfo8E43gIGSEyXgrsaJTdELGg-RLC5DlAdNXmNleyBgu5b7H-rr752t3FzEF9pHV4zqm7g32VhGv6V21tnDLyU114rE0xamqSTR-0Iy13SRKX4PnzOt_o84S1gKbYEBcWB0oxJKgI-DsZVbou8kv48GSAalNEvh-20Q",
    count: 32,
  },
  {
    id: "accessories",
    name: "Accessories",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuD55UADWRbrTE0WJ9tOhOztlhXKnkRPj8it-rucfoMLg_IL06ZFDRzKf_2PhyVWqmR3u_MVt9mfaaNd7MVBOdyJX481_fhIju_URJvO5A9nvQpHV7eqFWow3sGdRV-sy_Z2QbhNxu1m7zcFsLphGd1iyMSfWINdyouwtipl7hBYQW0VyhCh6cmQFt9jLiOPsrDOYodRM0x8yo0aCc29tpVbQv0klqISy_E1tCvh4I8cGB5_blu-sTYfkQ",
    count: 18,
  },
  {
    id: "shoes",
    name: "Shoes",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBtuJzbwhNizJ5CryJYajWHM7__k6tuo2NTA1TGNAaLaMIDPeqIWneq6B26rrmnoEK2hiyXDZMBsg5JgOzxUlUlAH2WmuoJTeuBmy1s1DpfXWist5g5TaE4lyQtCZfP7MS4cBRQ8kyWta9gAixDAf9G98r5gVYa7KBl2X2C9srAOmmupBF-RZT9ANvizJE14EZIrkZcWoKggpyZMWuXhAYRTKkUeojul0hjpy93ATOI3RwSrfY9S1bAeA",
    count: 15,
  },
];

export const collections: Collection[] = [
  {
    id: "summer",
    name: "Summer Collection",
    subtitle: "Light & Breezy",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCf2FKKs8TW_Z7MJNxnXf7EEjPhQ8KS6nzAql_A8gIsnBdjQYSMqFiQSvCbJHHE1cTrOtpz6Cu81MBZpvOK6Bq2Ztr4TUCbR9KmNSIvOWKh2JD_kN13Vjxn5nybo5rJKH9I8RdLdWTbkMlhlpK2UdHlQ7jjyTrhLmwQNTmOO4a_HzrW-N301xvLGD_XKWRK0rLyWq9j3qv2zeGM3a8OdWo_uMEXRYCsA2unf8ix5O8WXDW6JKuvu6pLyqLInOAMRZPSXtU",
    category: "women",
  },
  {
    id: "formal",
    name: "Formal Wear",
    subtitle: "Elegant & Sophisticated",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCYwnRyL7sSyPGZgnUwHmCqKlN4lSSgRFzfIkWeli1bI1xStD6VfAvBSujM7I6ppKJGLKxAtVpYOaLfu-5ZxTdrvlEIekb5LMu4J54xUhjKSQ1K2HGoQkcLSV5bw1ZjpdXdgCyfHQikyWvXTaLUkRURy5aLiiTsaA4mLY1s_MESyzumx39SYA8iB7CNPWIevmNo6M6ewZP_0qKENU-wl0lmuQuASuoA0oth7hMwbEWC1K1WT2uI4u5lqI-d3J14O_-MXhg",
    category: "men",
  },
  {
    id: "casual",
    name: "Casual Style",
    subtitle: "Comfortable & Trendy",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCyK_v1skP35j9-TnGVOctRgIyS5XtdD191TpcUlLn8ykwsZxFovXJkBuIDJOKLX-m6RCAqtHVM3b4B6mRNTTfHjSbf_W6pDeE0tO6orV1aaWg8xPHsfttTfK4ilYcSM-X43L8bvSva7nR3batvb6FoxhTAcJkIvSPN0r5snHHv_Jv8Zp1NSlBGJIqgL9MSU4rUxerUclamgy359eB5y7pgOk1MKltdHxXL7A0NAI0zEeHOV2X7UtvFJw",
    category: "accessories",
  },
];

export const products: Product[] = [
  {
    id: "p1",
    name: "Premium Leather Jacket",
    category: "Jackets",
    price: 299,
    originalPrice: 399,
    discount: 25,
    rating: 5,
    reviews: 156,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB2GTCZQRzHB1K2KUjGbDlNW5CnA3ffMrncZd7gpXLME_h97wOJBwTT98NuzW87kszzoZvxRB_SmzzKWbEb26-RKfo4jR_E4AR8VCe76OBzfN2FY4h_Jp6jtNJWqiPkR7iW_WwOMaIhS7TexXVFUbhoi_ddhnb7dqkn6uixKs7P94a2B-r8eFdAZZO9e7VtATDC4QG0Gc1HvCa6eROZ_KVIQtM6bus9_gt4XxRqeVEekoIRqPjmcP07bw",
    isNew: true,
    description: "Crafted from exceptionally soft, full-grain genuine leather, this iconic biker jacket delivers timeless attitude and unmatched durability. Featuring robust silver hardware, asymmetric front zip closure, multiple utilitarian pockets, and a luxurious quilted interior lining for superior comfort. Tailored for a modern, slim silhouette that molds perfectly to your body over time.",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Obsidian Black", hex: "#121212" },
      { name: "Chestnut Brown", hex: "#5C4033" },
    ],
    details: [
      "100% premium full-grain lambskin leather",
      "Asymmetric heavy-duty metal zipper",
      "Comfortable satin-quilted inner lining",
      "Two zippered hand pockets and one internal chest pocket",
      "Zippered expandable cuffs for adaptive fit",
    ],
  },
  {
    id: "p2",
    name: "Elegant Summer Dress",
    category: "Dresses",
    price: 150,
    originalPrice: 199,
    discount: 20,
    rating: 5,
    reviews: 203,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuD4VvL7icvrTJ0OAIfxszO0Wk08mmNCaFpeJnteMT8XJwN1zQNUlV-XkhDmd0GxTgrFZ2urfdPS9FOIM1WTJfB8v2JNtXhesJPNbV3wclKFCviC1doDmDQ8DQu6u03cW-2q7hllDEAaEj07ecCi_UPEEFdmCgC9YQgGN8y4d6nXf7FUJTNDU62a5b8339b9udHWVCA_RzlA_WlcMjIF38d3eJJn4SenxtnkZORM_RsNagi_aN22qfTiLA",
    isTrending: true,
    description: "The epitome of summer elegance, this dress features an eye-catching flowing silhouette, deep V-neckline, and an open cross-back design. Made with premium, light-as-air georgette fabric that drapes gracefully and moves beautifully with you. Perfect for sunset dinners, garden soirees, or premium weekend getaways.",
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { name: "Sunset Marigold", hex: "#E67E22" },
      { name: "Crimson Red", hex: "#C0392B" },
      { name: "Canary Yellow", hex: "#F1C40F" },
    ],
    details: [
      "High-grade lightweight georgette fabric",
      "Adjustable tie-back straps for custom bust fit",
      "Fitted empire waist with a cascading pleated skirt",
      "Concealed side zipper closure",
      "Breathable, non-static inner slip lining",
    ],
  },
  {
    id: "p3",
    name: "Classic Denim Jacket",
    category: "Jackets",
    price: 120,
    originalPrice: 179,
    discount: 30,
    rating: 4,
    reviews: 89,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC3VSDvlp8XMmVxZG_BrutaxbfotkyBIZ534tNZ-CxrAc04HIkeUAr2DHGGgvff7AyOOSNyCPW__oJKPqaOW5VZwzDlU_Qy4Hx1OVWMfi5fishydbxrfGzGaFgJe42TQC5-EDoEZqAcxfFbx1QOV5PVUT6XwQzkdbHth2Ez8dv9eh-QVr3dzAVy3T8XeLRQK5wGv7ZnNaJhmLywVCpHMyOUsacL2O89kmHTejmssoPeg5dPW0Jb4k7cQQ",
    isSale: true,
    description: "An absolute wardrobe essential made with authentic rigid cotton denim. Designed with classic truck styling, button cuffs, point collar, and copper buttons. This jacket has been pre-washed to give a subtle worn-in look and feel that only gets better with wear and age.",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Indigo Blue", hex: "#2E5894" },
      { name: "Vintage Light Blue", hex: "#A9C1D9" },
    ],
    details: [
      "100% heavyweight cotton denim",
      "Branded copper button shank closures",
      "Classic dual button-flap chest pockets",
      "Welt side hand pockets",
      "Adjustable button tabs at the back hem",
    ],
  },
  {
    id: "p4",
    name: "Designer Sneakers",
    category: "Shoes",
    price: 180,
    originalPrice: 240,
    discount: 25,
    rating: 5,
    reviews: 134,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCmG26EhQzoNR6E9ymcOfNa3_YcgyfYW9bL0xm3mlqAFiKg91UtpJI1mSU9dcJrVuT8l2i9NUc4EquD-Shovp4aJg0F6us5jYvkUggHEEDusS5NcWpbbyX_Ep8I3IzKL9-qNHRILeyzcAEb60Fwto8PDbNy5kXmh3ZEou4-eU3EP_nhbmgilLgswhsH1A0TLUO09XfqK-UiyPtLbLRu2bWMwEyhpiaxjLbauOt5MfVWwITC611HBwE-HA",
    isBestseller: true,
    description: "These premium minimalist sneakers are crafted with buttery-soft calf leather and detailed with clean suede overlays. Engineered with an ultra-light shock-absorbing cupsole and an ergonomic memory-foam insole for unparalleled all-day comfort. Perfect for elevated street style.",
    sizes: ["39", "40", "41", "42", "43", "44"],
    colors: [
      { name: "Alabaster White", hex: "#F5F5F0" },
      { name: "Desert Sand", hex: "#D2B48C" },
    ],
    details: [
      "Full-grain calfskin leather and Italian suede panels",
      "Fully lined with breathable calf leather",
      "Reinforced custom rubber cupsole for lasting grip",
      "Premium wax-coated cotton laces",
      "Handcrafted and stitched detailing",
    ],
  },
  {
    id: "p5",
    name: "Cashmere Turtleneck Sweater",
    category: "Dresses", // Grouping under similar or Men
    price: 140,
    originalPrice: 190,
    discount: 26,
    rating: 5,
    reviews: 72,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCf2FKKs8TW_Z7MJNxnXf7EEjPhQ8KS6nzAql_A8gIsnBdjQYSMqFiQSvCbJHHE1cTrOtpz6Cu81MBZpvOK6Bq2Ztr4TUCbR9KmNSIvOWKh2JD_kN13Vjxn5nybo5rJKH9I8RdLdWTbkMlhlpK2UdHlQ7jjyTrhLmwQNTmOO4a_HzrW-N301xvLGD_XKWRK0rLyWq9j3qv2zeGM3a8OdWo_uMEXRYCsA2unf8ix5O8WXDW6JKuvu6pLyqLInOAMRZPSXtU", // Alternate reuse
    isTrending: true,
    description: "Knitted from 100% fine-gauge Mongolian cashmere, this turtleneck sweater sets a new standard for luxury knitwear. Remarkably light yet exceptionally warm, it features a ribbed collar, hem, and cuffs for a structured silhouette. A timeless classic that layers beautifully under any tailored coat.",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Heather Grey", hex: "#B2B2B2" },
      { name: "Midnight Black", hex: "#0F0F0F" },
      { name: "Cream Ivory", hex: "#F9F6EE" },
    ],
    details: [
      "100% pure Grade-A Mongolian cashmere",
      "Luxuriously soft 12-gauge knit structure",
      "Double-ply ribbed turtleneck design",
      "Handwash or dry clean only",
    ],
  },
  {
    id: "p6",
    name: "Minimalist Leather Watch",
    category: "Accessories",
    price: 220,
    originalPrice: 299,
    discount: 26,
    rating: 5,
    reviews: 95,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuD55UADWRbrTE0WJ9tOhOztlhXKnkRPj8it-rucfoMLg_IL06ZFDRzKf_2PhyVWqmR3u_MVt9mfaaNd7MVBOdyJX481_fhIju_URJvO5A9nvQpHV7eqFWow3sGdRV-sy_Z2QbhNxu1m7zcFsLphGd1iyMSfWINdyouwtipl7hBYQW0VyhCh6cmQFt9jLiOPsrDOYodRM0x8yo0aCc29tpVbQv0klqISy_E1tCvh4I8cGB5_blu-sTYfkQ", // Reuse accessories image
    isNew: true,
    description: "Designed in our Swiss studio, this timepiece embodies minimalism with a striking matte black 40mm case and genuine Italian leather strap. Driven by high-precision Miyota quartz movement and shielded by scratch-resistant mineral crystal glass. Subtle details make it a highly versatile design statement.",
    sizes: ["One Size"],
    colors: [
      { name: "Stealth Black", hex: "#222222" },
      { name: "Cognac Tan", hex: "#B37A4C" },
    ],
    details: [
      "Precision Japanese Miyota Quartz movement",
      "40mm surgical-grade 316L stainless steel case",
      "Strap width: 20mm genuine vegetable-tanned leather",
      "Water resistant up to 5 ATM (50 meters)",
      "Ultra-slim 7mm profile for a lightweight wrist feel",
    ],
  },
  {
    id: "p7",
    name: "Tailored Wool Trench Coat",
    category: "Jackets",
    price: 310,
    originalPrice: 420,
    discount: 26,
    rating: 5,
    reviews: 48,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCYwnRyL7sSyPGZgnUwHmCqKlN4lSSgRFzfIkWeli1bI1xStD6VfAvBSujM7I6ppKJGLKxAtVpYOaLfu-5ZxTdrvlEIekb5LMu4J54xUhjKSQ1K2HGoQkcLSV5bw1ZjpdXdgCyfHQikyWvXTaLUkRURy5aLiiTsaA4mLY1s_MESyzumx39SYA8iB7CNPWIevmNo6M6ewZP_0qKENU-wl0lmuQuASuoA0oth7hMwbEWC1K1WT2uI4u5lqI-d3J14O_-MXhg", // Reuse coat
    isBestseller: true,
    description: "Wrap yourself in warmth and architectural structure. This tailored long trench coat is crafted from premium heavy wool blend that is naturally water-repellent. Features structured padded shoulders, matching waist tie belt, notched lapels, and custom double-breasted horn button closures.",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Camel", hex: "#C19A6B" },
      { name: "Charcoal Black", hex: "#2E3033" },
    ],
    details: [
      "Premium 80% wool and 20% cashmere blend",
      "Double-breasted front with horn button fastening",
      "Matching self-tie belt with belt loops",
      "Deep side slant pockets and button-through back vent",
      "Fully lined in soft viscose for easy layering",
    ],
  },
  {
    id: "p8",
    name: "Urban Active Hoody",
    category: "Jackets",
    price: 95,
    originalPrice: 130,
    discount: 27,
    rating: 4,
    reviews: 112,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCyK_v1skP35j9-TnGVOctRgIyS5XtdD191TpcUlLn8ykwsZxFovXJkBuIDJOKLX-m6RCAqtHVM3b4B6mRNTTfHjSbf_W6pDeE0tO6orV1aaWg8xPHsfttTfK4ilYcSM-X43L8bvSva7nR3batvb6FoxhTAcJkIvSPN0r5snHHv_Jv8Zp1NSlBGJIqgL9MSU4rUxerUclamgy359eB5y7pgOk1MKltdHxXL7A0NAI0zEeHOV2X7UtvFJw", // Reuse casual
    isSale: true,
    description: "Designed for comfort on the move, this hoodie is made from premium heavyweight French Terry loopback cotton. Detailed with a heavy double-lined hood, high neck collar, discrete side zip pockets, and clean flatlock stitched seams. It offers structured comfort for travel and active days.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Charcoal", hex: "#3A3B3C" },
      { name: "Olive Drab", hex: "#4B5320" },
    ],
    details: [
      "100% heavyweight loopback French Terry cotton",
      "Double-layered drawstring-free structural hood",
      "Concealed low-profile zip hand pockets",
      "Preshrunk fabric to hold shape over infinite washes",
    ],
  },
];
